INSERT INTO DRUG_DETAILS VALUES ('PR1', 'Paracetamol', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'Priya');
INSERT INTO DRUG_DETAILS VALUES ('CR2', 'Crocin', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'Aman');
INSERT INTO DRUG_DETAILS VALUES ('PD3', 'Penadol', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'Madhuri');
INSERT INTO DRUG_DETAILS VALUES ('DD4', 'Dolo', parsedatetime('22-11-2024', 'dd-MM-yyyy'), parsedatetime('22-22-2020', 'dd-MM-yyyy'), 'Kedar');


INSERT INTO DRUG_LOCATION_DETAILS VALUES('1', 'Chennai', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('2', 'Bangalore', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('3', 'Pune', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('4', 'Hyderabad', 500, 'PR1');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('5', 'Chennai', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('6', 'Bangalore', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('7', 'Pune', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('8', 'Hyderabad', 500, 'CR2');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('9', 'Chennai', 500, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('10', 'Bangalore', 500, 'PD3');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('11', 'Hyderabad', 500, 'DD4');
INSERT INTO DRUG_LOCATION_DETAILS VALUES('12', 'Bangalore', 500, 'DD4');